package com.nickjgski.splatoongear

import android.content.Context
import androidx.room.Database
import androidx.room.Room
import androidx.room.RoomDatabase
import androidx.sqlite.db.SupportSQLiteDatabase

@Database(entities = [Wearable::class], version = 1, exportSchema = false)
abstract class WearableDatabase: RoomDatabase() {

    abstract fun wearableDao(): WearableDao

    companion object {

        @Volatile
        private var INSTANCE: WearableDatabase? = null

        fun getInstance(context: Context): WearableDatabase =
            INSTANCE ?: synchronized(this) {
                INSTANCE ?: buildDatabase(context).also { INSTANCE = it }
            }

        private fun buildDatabase(context: Context) =
            Room.databaseBuilder(
                context.applicationContext,
                WearableDatabase::class.java, "Wearable.db"
            )
                // prepopulate the database after onCreate was called
                .addCallback(object : Callback() {
                    override fun onCreate(db: SupportSQLiteDatabase) {
                        super.onCreate(db)
                        // insert the data on the IO Thread
                        Thread( Runnable {
                            getInstance(context).wearableDao().insertAll(PREPOPULATE_DATA)
                        }).start()
                    }
                })
                .build()

        val PREPOPULATE_DATA: List<Wearable> = listOf(
            Wearable("18K Aviators", "Headgear", "Last-Ditch Effort", 3, "3/35/S2_Gear_Headgear_18K_Aviators.png"),
            Wearable("Anglerfish Mask", "Headgear", "Ink Saver (Main)", 3, "9/98/S2_Gear_Headgear_Anglerfish_Mask.png"),
            Wearable("Annaki Beret", "Headgear", "Ink Resistance Up", 3, "f/f4/S2_Gear_Headgear_Annaki_Beret.png"),
            Wearable("Annaki Beret & Glasses", "Headgear", "Ink Saver (Main)", 3, "9/9c/S2_Gear_Headgear_Annaki_Beret_%26_Glasses.png"),
            Wearable("Annaki Mask", "Headgear", "Opening Gambit", 2, "8/8a/S2_Gear_Headgear_Annaki_Mask.png"),
            Wearable("Armor Helmet Replica", "Headgear", "Tenacity", 2, "0/0b/S2_Gear_Headgear_Armor_Helmet_Replica.png"),
            Wearable("B-ball Headband", "Headgear", "Opening Gambit", 1, "0/0b/S2_Gear_Headgear_B-ball_Headband.png"),
            Wearable("Backwards Cap", "Headgear", "Quick Respawn", 1, "3/38/S2_Gear_Headgear_Backwards_Cap.png"),
            Wearable("Bamboo Hat", "Headgear", "Ink Saver (Main)", 2, "9/9b/S2_Gear_Headgear_Bamboo_Hat.png"),
            Wearable("Beekeeper Hat", "Headgear", "Random", 3, "8/8d/S2_Gear_Headgear_Beekeeper_Hat.png"),
            Wearable("Bike Helmet", "Headgear", "Ink Recovery Up", 2, "2/25/S2_Gear_Headgear_Bike_Helmet.png"),
            Wearable("Black Arrowbands", "Headgear", "Tenacity", 2, "1/16/S2_Gear_Headgear_Black_Arrowbands.png"),
            Wearable("Black FishFry Bandana", "Headgear", "Bomb Defense Up DX", 1, "3/38/S2_Gear_Headgear_Black_FishFry_Bandana.png"),
            Wearable("Blowfish Bell Hat", "Headgear", "Ink Recovery Up", 1, "5/50/S2_Gear_Headgear_Blowfish_Bell_Hat.png"),
            Wearable("Blowfish Newsie", "Headgear", "Quick Super Jump", 2, "d/d7/S2_Gear_Headgear_Blowfish_Newsie.png"),
            Wearable("Bobble Hat", "Headgear", "Quick Super Jump", 2, "4/44/S2_Gear_Headgear_Bobble_Hat.png"),
            Wearable("Bucket Hat", "Headgear", "Special Saver", 1, "e/e5/S2_Gear_Headgear_Bucket_Hat.png"),
            Wearable("Camo Mesh", "Headgear", "Swim Speed Up", 1, "2/22/S2_Gear_Headgear_Camo_Mesh.png"),
            Wearable("Camping Hat", "Headgear", "Special Power Up", 1, "0/03/S2_Gear_Headgear_Camping_Hat.png"),
            Wearable("Cap of Legend", "Headgear", "Random", 3, "0/03/S2_Gear_Headgear_Cap_of_Legend.png"),
            Wearable("Classic Straw Boater", "Headgear", "Special Power Up", 2, "f/f1/S2_Gear_Headgear_Classic_Straw_Boater.png"),
            Wearable("Conductor Cap", "Headgear", "Sub Power Up", 2, "3/3d/S2_Gear_Headgear_Conductor_Cap.png"),
            Wearable("Cycle King Cap", "Headgear", "Bomb Defense Up DX", 2, "d/d6/S2_Gear_Headgear_Cycle_King_Cap.png"),
            Wearable("Cycling Cap", "Headgear", "Sub Power Up", 1, "f/f0/S2_Gear_Headgear_Cycling_Cap.png"),
            Wearable("Deck Tackle Visor Helmet", "Headgear", "Sub Power Up", 3, "c/c5/S2_Gear_Headgear_Deca_Tackle_Visor_Helmet.png"),
            Wearable("Designer Headphones", "Headgear", "Ink Saver (Sub)", 2, "9/91/S2_Gear_Headgear_Designer_Headphones.png"),
            Wearable("Digi-Camo Forge Mask", "Headgear", "Swim Speed Up", 2, "c/c6/S2_Gear_Headgear_Digi-Camo_Forge_Mask.png"),
            Wearable("Do-Rag, Cap, and Glasses", "Headgear", "Main Power Up", 3, "f/f7/S2_Gear_Headgear_Do-Rag%2C_Cap%2C_%26_Glasses.png"),
            Wearable("Double Egg Shades", "Headgear", "Run Speed Up", 2, "3/32/S2_Gear_Headgear_Double_Egg_Shades.png"),
            Wearable("Dust Blocker 2000", "Headgear", "Random", 3, "b/bd/S2_Gear_Headgear_Dust_Blocker_2000.png"),
            Wearable("Eminence Cuff", "Headgear", "Ink Saver Main", 3, "7/75/S2_Gear_Headgear_Eminence_Cuff.png"),
            Wearable("Eel-Cake Hat", "Headgear", "Quick Respawn", 3, "7/74/S2_Gear_Headgear_Eel-Cake_Hat.png"),
            Wearable("Enchanted Hat", "Headgear", "Ink Saver (Main)", 2, "6/62/S2_Gear_Headgear_Enchanted_Hat.png"),
            Wearable("Face Visor", "Headgear", "Bomb Defense Up DX", 3, "8/83/S2_Gear_Headgear_Face_Visor.png"),
            Wearable("Fake Contacts", "Headgear", "Special Charge Up", 2, "4/40/S2_Gear_Headgear_Fake_Contacts.png"),
            Wearable("Festival Party Cone", "Headgear", "Main Power Up", 3, "c/cf/S2_Gear_Headgear_Festive_Party_Cone.png"),
            Wearable("Firefin Facemask", "Headgear", "Run Speed Up", 1, "7/73/S2_Gear_Headgear_Firefin_Facemask.png"),
            Wearable("FishFry Biscuit Bandana", "Headgear", "Special Power Up", 1, "6/68/S2_Gear_Headgear_FishFry_Biscuit_Bandana.png"),
            Wearable("FishFry Visor", "Headgear", "Special Charge Up", 1, "7/73/S2_Gear_Headgear_FishFry_Visor.png"),
            Wearable("Five-Panel Cap", "Headgear", "Comeback", 2, "8/8c/S2_Gear_Headgear_Five-Panel_Cap.png"),
            Wearable("Forge Mask", "Headgear", "Main Power Up", 1, "5/59/S2_Gear_Headgear_Forge_Mask.png"),
            Wearable("Fresh Fish Head", "Headgear", "Comeback", 2, "7/7e/S2_Gear_Headgear_Fresh_Fish_Head.png"),
            Wearable("Fugu Bell Hat", "Headgear", "Quick Respawn", 2, "e/e2/S2_Gear_Headgear_Fugu_Bell_Hat.png"),
            Wearable("Full Moon Glasses", "Headgear", "Quick Super Jump", 1, "7/74/S2_Gear_Headgear_Full_Moon_Glasses.png"),
            Wearable("Gas Mask", "Headgear", "Tenacity", 3, "1/13/S2_Gear_Headgear_Gas_Mask.png"),
            Wearable("Golden Toothpick", "Headgear", "Special Charge Up", 3, "0/0c/S2_Gear_Headgear_Golden_Toothpick.png"),
            Wearable("Golf Visor", "Headgear", "Run Speed Up", 1, "6/64/S2_Gear_Headgear_Golf_Visor.png"),
            Wearable("Green Novelty Visor", "Headgear", "Special Saver", 3, "0/0a/S2_Gear_Headgear_Green_Novelty_Visor.png"),
            Wearable("Half-Rim Glasses", "Headgear", "Special Power Up", 2, "9/94/S2_Gear_Headgear_Half-Rim_Glasses.png"),
            Wearable("Headlamp Helmet", "Headgear", "Random", 3, "a/aa/S2_Gear_Headgear_Headlamp_Helmet.png"),
            Wearable("Hero Headphones Replica", "Headgear", "Special Saver", 2, "2/2d/S2_Gear_Headgear_Hero_Headphones_Replica.png"),
            Wearable("Hero Headset Replica", "Headgear", "Run Speed Up", 2, "4/45/S2_Gear_Headgear_Hero_Headset_Replica.png"),
            Wearable("Hickory Work Cap", "Headgear", "Special Power Up", 3, "8/8f/S2_Gear_Headgear_Hickory_Work_Cap.png"),
            Wearable("Hockey Helmet", "Headgear", "Main Power Up", 3, "a/a6/S2_Gear_Headgear_Hockey_Helmet.png"),
            Wearable("Hockey Mask", "Headgear", "Ink Recovery Up", 3, "a/a9/S2_Gear_Headgear_Hockey_Mask.png"),
            Wearable("Hothouse Hat", "Headgear", "Ink Resistance Up", 2, "c/cd/S2_Gear_Headgear_Hothouse_Hat.png"),
            Wearable("House-Tag Denim Cap", "Headgear", "Special Charge Up", 2, "b/b2/S2_Gear_Headgear_House-Tag_Denim_Cap.png"),
            Wearable("Ink-Guard Goggles", "Headgear", "Run Speed Up", 3, "4/45/S2_Gear_Headgear_Ink-Guard_Goggles.png"),
            Wearable("Jellyvader Cap", "Headgear", "Ink Saver (Sub)", 3, "3/34/S2_Gear_Headgear_Jellyvader_Cap.png"),
            Wearable("Jet Cap", "Headgear", "Special Saver", 1, "8/85/S2_Gear_Headgear_Jet_Cap.png"),
            Wearable("Jogging Headband", "Headgear", "Ink Saver (Sub)", 1, "4/45/S2_Gear_Headgear_Jogging_Headband.png"),
            Wearable("Jungle Hat", "Headgear", "Ink Saver (Main)", 3, "0/0b/S2_Gear_Headgear_Jungle_Hat.png"),
            Wearable("King Facemask", "Headgear", "Ink Saver (Sub)", 1, "a/a4/S2_Gear_Headgear_King_Facemask.png"),
            Wearable("King Flip Mesh", "Headgear", "Run Speed Up", 2, "4/48/S2_Gear_Headgear_King_Flip_Mesh.png"),
            Wearable("Knitted Hat", "Headgear", "Ink Resistance Up", 1, "9/9b/S2_Gear_Headgear_Knitted_Hat.png"),
            Wearable("Koshien Bandana", "Headgear", "Swim Speed Up", 1, "3/3c/S2_Gear_Headgear_Koshien_Bandana.png"),
            Wearable("Kyonshi Hat", "Headgear", "Run Speed Up", 1, "b/b9/S2_Gear_Headgear_Kyonshi_Hat.png"),
            Wearable("Lightweight Cap", "Headgear", "Swim Speed Up", 1, "4/48/S2_Gear_Headgear_Lightweight_Cap.png"),
            Wearable("Li'l Devil Horns", "Headgear", "Ink Saver (Sub)", 3, "9/9a/S2_Gear_Headgear_Li%27l_Devil_Horns.png"),
            Wearable("Long-Billed Cap", "Headgear", "Ink Recovery Up", 3, "1/13/S2_Gear_Headgear_Long-Billed_Cap.png"),
            Wearable("Marinated Headphones", "Headgear", "Special Saver", 2, "7/70/S2_Gear_Headgear_Marinated_Headphones.png"),
            Wearable("Matte Bike Helmet", "Headgear", "Sub Power Up", 3, "1/18/S2_Gear_Headgear_Matte_Bike_Helmet.png"),
            Wearable("Mecha Head HTR", "Headgear", "Main Power Up", 3, "3/3e/S2_Gear_Headgear_Mecha_Head_-_HTR.png"),
            Wearable("Moist Gillie Helmet", "Headgear", "Run Speed Up", 3, "8/8c/S2_Gear_Headgear_Moist_Ghillie_Helmet.png"),
            Wearable("Motocross Nose Guard", "Headgear", "Special Charge Up", 3, "5/5c/S2_Gear_Headgear_Motocross_Nose_Guard.png"),
            Wearable("Mountie", "Headgear", "Special Charge Up", 3, "3/3c/S2_Gear_Headgear_Mountie_Hat.png"),
            Wearable("MTB Helmet", "Headgear", "Tenacity", 3, "0/01/S2_Gear_Headgear_MTB_Helmet.png"),
            Wearable("New Year's Glasses DX", "Headgear", "Special Charge Up", 3, "8/80/S2_Gear_Headgear_New_Year%27s_Glasses_DX.png"),
            Wearable("Noise Cancelers", "Headgear", "Quick Respawn", 3, "2/20/S2_Gear_Headgear_Noise_Cancelers.png"),
            Wearable("Null Visor Replica", "Headgear", "Special Power Up", 2, "e/ec/S2_Gear_Headgear_Null_Visor_Replica.png"),
            Wearable("Oceanic Hard Hat", "Headgear", "Random", 3, "1/17/S2_Gear_Headgear_Oceanic_Hard_Hat.png"),
            Wearable("Octo Tackle Helmet Deco", "Headgear", "Bomb Defense Up DX", 3, "7/72/S2_Gear_Headgear_Octo_Tackle_Helmet_Deco.png"),
            Wearable("Octoglasses", "Headgear", "Last-Ditch Effort", 3, "7/78/S2_Gear_Headgear_Octoglasses.png"),
            Wearable("Octoking Facemask", "Headgear", "Tenacity", 1, "3/31/S2_Gear_Headgear_Octoking_Facemask.png"),
            Wearable("Octoleet Goggles", "Headgear", "Random", 3, "1/1c/S2_Gear_Headgear_Octoleet_Goggles.png"),
            Wearable("Octoling Shades", "Headgear", "Last-Ditch Effort", 2, "9/91/S2_Gear_Headgear_Octoling_Shades.png"),
            Wearable("Old-Timey Hat", "Headgear", "Comeback", 2, "1/1e/S2_Gear_Headgear_Old-Timey_Hat.png"),
            Wearable("Orange Novelty Visor", "Headgear", "Last-Ditch Effort", 3, "9/94/S2_Gear_Headgear_Orange_Novelty_Visor.png"),
            Wearable("Paintball Mask", "Headgear", "Comeback", 3, "a/ae/S2_Gear_Headgear_Paintball_Mask.png"),
            Wearable("Painter's Mask", "Headgear", "Main Power Up", 2, "d/d4/S2_Gear_Headgear_Painter%27s_Mask.png"),
            Wearable("Paisley Bandana", "Headgear", "Ink Saver (Sub)", 1, "c/c1/S2_Gear_Headgear_Paisley_Bandana.png"),
            Wearable("Patched Hat", "Headgear", "Main Power Up", 2, "d/d1/S2_Gear_Headgear_Patched_Hat.png"),
            Wearable("Pearlescent Crown", "Headgear", "Bomb Defense Up DX", 2, "7/77/S2_Gear_Headgear_Pearlescent_Crown.png"),
            Wearable("Pilot Goggles", "Headgear", "Sub Power Up", 2, "f/f9/S2_Gear_Headgear_Pilot_Goggles.png"),
            Wearable("Pilot Hat", "Headgear", "Ink Resistance Up", 3, "3/3e/S2_Gear_Headgear_Pilot_Hat.png"),
            Wearable("Pink Novelty Visor", "Headgear", "Tenacity", 3, "9/92/S2_Gear_Headgear_Pink_Novelty_Visor.png"),
            Wearable("Power Mask", "Headgear", "Bomb Defense Up DX", 2, "4/4e/S2_Gear_Headgear_Power_Mask.png"),
            Wearable("Power Mask Mk 1", "Headgear", "Ink Resistance Up", 2, "a/a4/S2_Gear_Headgear_Power_Mask_Mk_I.png"),
            Wearable("Purple Novelty Visor", "Headgear", "Ink Resistance Up", 3, "7/74/S2_Gear_Headgear_Purple_Novelty_Visor.png"),
            Wearable("Retro Specs", "Headgear", "Quick Respawn", 1, "2/2b/S2_Gear_Headgear_Retro_Specs.png"),
            Wearable("Sailor Cap", "Headgear", "Random", 3, "2/2b/S2_Gear_Headgear_Sailor_Cap.png"),
            Wearable("Safari Hat", "Headgear", "Last-Ditch Effort", 2, "4/47/S2_Gear_Headgear_Safari_Hat.png"),
            Wearable("Samurai Helmet", "Headgear", "Quick Super Jump", 2, "4/4b/S2_Gear_Headgear_Samurai_Helmet.png"),
            Wearable("Seashell Bamboo Hat", "Headgear", "Quick Respawn", 2, "d/da/S2_Gear_Headgear_Seashell_Bamboo_Hat.png"),
            Wearable("Sennyu Bon Bon Beanie", "Headgear", "Ink Saver (Sub)", 3, "e/e2/S2_Gear_Headgear_Sennyu_Bon_Bon_Beanie.png"),
            Wearable("Sennyu Goggles", "Headgear", "Ink Resistance Up", 3, "a/aa/S2_Gear_Headgear_Sennyu_Goggles.png"),
            Wearable("Sennyu Headphones", "Headgear", "Ink Saver (Main)", 3, "a/a6/S2_Gear_Headgear_Sennyu_Headphones.png"),
            Wearable("Sennyu Specs", "Headgear", "Swim Speed Up", 3, "6/6a/S2_Gear_Headgear_Sennyu_Specs.png"),
            Wearable("Short Beanie", "Headgear", "Ink Saver (Main)", 1, "b/bd/S2_Gear_Headgear_Short_Beanie.png"),
            Wearable("Skate Helmet", "Headgear", "Special Saver", 2, "a/a7/S2_Gear_Headgear_Skate_Helmet.png"),
            Wearable("Skull Bandana", "Headgear", "Special Saver", 3, "d/dc/S2_Gear_Headgear_Skull_Bandana.png"),
            Wearable("Sneaky Beanie", "Headgear", "Swim Speed Up", 2, "9/9a/S2_Gear_Headgear_Sneaky_Beanie.png"),
            Wearable("Snorkel Mask", "Headgear", "Ink Saver (Sub)", 2, "b/bd/S2_Gear_Headgear_Snorkel_Mask.png"),
            Wearable("Soccer Headband", "Headgear", "Tenacity", 2, "c/c6/S2_Gear_Headgear_Soccer_Headband.png"),
            Wearable("Special Forces Beret", "Headgear", "Opening Gambit", 3, "d/dc/S2_Gear_Headgear_Special_Forces_Beret.png"),
            Wearable("Splash Goggles", "Headgear", "Bomb Defense Up DX", 2, "d/de/S2_Gear_Headgear_Splash_Goggles.png"),
            Wearable("Sporty Bobble Hat", "Headgear", "Tenacity", 1, "f/f0/S2_Gear_Headgear_Sporty_Bobble_Hat.png"),
            Wearable("Squash Headband", "Headgear", "Special Saver", 1, "5/56/S2_Gear_Headgear_Squash_Headband.png"),
            Wearable("Squid Clip-Ons", "Headgear", "Opening Gambit", 2, "7/72/S2_Gear_Headgear_Squid_Clip-Ons.png"),
            Wearable("Squid Facemask", "Headgear", "Ink Saver (Main)", 1, "2/22/S2_Gear_Headgear_Squid_Facemask.png"),
            Wearable("Squid Hairclip", "Headgear", "Swim Speed Up", 2, "f/fa/S2_Gear_Headgear_Squid_Hairclip.png"),
            Wearable("Squid Nordic", "Headgear", "Comeback", 3, "8/86/S2_Gear_Headgear_Squid_Nordic.png"),
            Wearable("Squid Stitch-Cap", "Headgear", "Opening Gambit", 3, "d/df/S2_Gear_Headgear_Squid-Stitch_Cap.png"),
            Wearable("Squidfin Hook Cans", "Headgear", "Ink Resistance Up", 2, "1/1d/S2_Gear_Headgear_Squidfin_Hook_Cans.png"),
            Wearable("Squidlife Headphones", "Headgear", "Ink Recovery Up", 3, "7/73/S2_Gear_Headgear_Squidlife_Headphones.png"),
            Wearable("Squidvader Cap", "Headgear", "Special Charge Up", 1, "c/cd/S2_Gear_Headgear_Squidvader_Cap.png"),
            Wearable("Squinja Mask", "Headgear", "Quick Respawn", 2, "e/e5/S2_Gear_Headgear_Squinja_Mask.png"),
            Wearable("Stealth Goggles", "Headgear", "Swim Speed Up", 3, "7/76/S2_Gear_Headgear_Stealth_Goggles.png"),
            Wearable("Steel Helm", "Headgear", "Special Charge Up", 2, "8/80/S2_Gear_Headgear_Steel_Helm.png"),
            Wearable("Straw Boater", "Headgear", "Quick Super Jump", 1, "d/d9/S2_Gear_Headgear_Straw_Boater.png"),
            Wearable("Streetstyle Cap", "Headgear", "Ink Saver (Sub)", 1, "3/32/S2_Gear_Headgear_Streetstyle_Cap.png"),
            Wearable("Striped Beanie", "Headgear", "Opening Gambit", 1, "c/c5/S2_Gear_Headgear_Striped_Beanie.png"),
            Wearable("Studio Headphones", "Headgear", "Ink Saver (Main)", 2, "6/62/S2_Gear_Headgear_Studio_Headphones.png"),
            Wearable("Studio Octophones", "Headgear", "Ink Recovery Up", 3, "/c/cc/S2_Gear_Headgear_Studio_Octophones.png"),
            Wearable("Sun Visor", "Headgear", "Sub Power Up", 2, "4/45/S2_Gear_Headgear_Sun_Visor.png"),
            Wearable("SV925 Circle Shades", "Headgear", "Swim Speed Up", 3, "6/6a/S2_Gear_Headgear_SV925_Circle_Shades.png"),
            Wearable("Swim Goggles", "Headgear", "Last-Ditch Effort", 1, "2/25/S2_Gear_Headgear_Swim_Goggles.png"),
            Wearable("Takoroka Mesh", "Headgear", "Bomb Defense Up DX", 1, "6/6a/S2_Gear_Headgear_Takoroka_Mesh.png"),
            Wearable("Takoroka Visor", "Headgear", "Quick Super Jump", 3, "b/ba/S2_Gear_Headgear_Takoroka_Visor.png"),
            Wearable("Tennis Headband", "Headgear", "Comeback", 1, "b/b5/S2_Gear_Headgear_Tennis_Headband.png"),
            Wearable("Tinted Shades", "Headgear", "Last-Ditch Effort", 1, "e/e0/S2_Gear_Headgear_Tinted_Shades.png"),
            Wearable("Toni Kensa Goggles", "Headgear", "Comeback", 1, "d/d3/S2_Gear_Headgear_Toni_Kensa_Goggles.png"),
            Wearable("Treasure Hunter", "Headgear", "Ink Recovery Up", 2, "c/c4/S2_Gear_Headgear_Treasure_Hunter.png"),
            Wearable("Tulip Parasol", "Headgear", "Ink Resistance Up", 1, "5/58/S2_Gear_Headgear_Tulip_Parasol.png"),
            Wearable("Twisty Headband", "Headgear", "Special Power Up", 3, "f/f2/S2_Gear_Headgear_Twisty_Headband.png"),
            Wearable("Two-Stripe Mesh", "Headgear", "Special Saver", 1, "a/a7/S2_Gear_Headgear_Two-Stripe_Mesh.png"),
            Wearable("Urchins Cap", "Headgear", "Sub Power Up", 1, "a/a1/S2_Gear_Headgear_Urchins_Cap.png"),
            Wearable("Visor Skate Helmet", "Headgear", "Last-Ditch Effort", 3, "5/5d/S2_Gear_Headgear_Visor_Skate_Helmet.png"),
            Wearable("Welding Mask", "Headgear", "Random", 3, "d/d8/S2_Gear_Headgear_Welding_Mask.png"),
            Wearable("White Arrowbands", "Headgear", "Special Power Up", 3, "f/f3/S2_Gear_Headgear_White_Arrowbands.png"),
            Wearable("White Headband", "Headgear", "Ink Recovery Up", 1, "8/82/S2_Gear_Headgear_White_Headband.png"),
            Wearable("Woolly Urchins Classic", "Headgear", "Comeback", 2, "f/f6/S2_Gear_Headgear_Woolly_Urchins_Classic.png"),
            Wearable("Worker's Cap", "Headgear", "Random", 3, "6/6d/S2_Gear_Headgear_Worker%27s_Cap.png"),
            Wearable("Worker's Head Towel", "Headgear", "Random", 3, "0/07/S2_Gear_Headgear_Worker%27s_Head_Towel.png"),
            Wearable("Yamagiri Beanie", "Headgear", "Main Power Up", 1, "e/e8/S2_Gear_Headgear_Yamagiri_Beanie.png"),
            Wearable("Zekko Cap", "Headgear", "Opening Gambit", 2, "6/6b/S2_Gear_Headgear_Zekko_Cap.png"),
            Wearable("Zekko Mesh", "Headgear", "Quick Super Jump", 1, "e/eb/S2_Gear_Headgear_Zekko_Mesh.png"),
            Wearable("Aloha Shirt", "Clothing", "Ink Recovery Up", 1, "a/a0/S2_Gear_Clothing_Aloha_Shirt.png"),
            Wearable("Anchor Life Vest", "Clothing", "Random", 3, "1/1b/S2_Gear_Clothing_Anchor_Life_Vest.png"),
            Wearable("Anchor Sweat", "Clothing", "Main Power Up", 2, "a/a7/S2_Gear_Clothing_Anchor_Sweat.png"),
            Wearable("Annaki Blue Cuff", "Clothing", "Special Saver", 2, "e/e4/S2_Gear_Clothing_Annaki_Blue_Cuff.png"),
            Wearable("Annaki Drive Tee", "Clothing", "Thermal Ink", 2, "d/d4/S2_Gear_Clothing_Annaki_Drive_Tee.png"),
            Wearable("Annaki Evolution Tee", "Clothing", "Respawn Punisher", 3, "5/57/S2_Gear_Clothing_Annaki_Evolution_Tee.png"),
            Wearable("Annaki Flannel Hoodie", "Clothing", "Bomb Defense Up DX", 3, "d/d6/S2_Gear_Clothing_Annaki_Flannel_Hoodie.png"),
            Wearable("Annaki Polpo-Pic Tee", "Clothing", "Run Speed Up", 3, "c/c8/S2_Gear_Clothing_Annaki_Polpo-Pic_Tee.png"),
            Wearable("Annaki Red Cuff", "Clothing", "Haunt", 2, "7/7d/S2_Gear_Clothing_Annaki_Red_Cuff.png"),
            Wearable("Annaki Yellow Cuff", "Clothing", "Quick Respawn", 2, "7/7f/S2_Gear_Clothing_Annaki_Yellow_Cuff.png"),
            Wearable("Armor Jacket Replica", "Clothing", "Special Charge Up", 2, "e/e1/S2_Gear_Clothing_Armor_Jacket_Replica.png"),
            Wearable("B-Ball Jersey (Away)", "Clothing", "Ink Saver (Sub)", 1, "5/53/S2_Gear_Clothing_B-ball_Jersey_%28Away%29.png"),
            Wearable("B-Ball Jersey (Home)", "Clothing", "Special Saver", 2, "d/dc/S2_Gear_Clothing_B-ball_Jersey_%28Home%29.png"),
            Wearable("Baby-Jelly Shirt", "Clothing", "Bomb Defense Up DX", 1, "4/4f/S2_Gear_Clothing_Baby-Jelly_Shirt.png"),
            Wearable("Baby-Jelly Shirt & Tie", "Clothing", "Main Power Up", 2, "3/31/S2_Gear_Clothing_Baby-Jelly_Shirt_%26_Tie.png"),
            Wearable("Baseball Jersey", "Clothing", "Special Charge Up", 3, "c/c7/S2_Gear_Clothing_Baseball_Jersey.png"),
            Wearable("Basic Tee", "Clothing", "Quick Respawn", 1, "1/1b/S2_Gear_Clothing_Basic_Tee.png"),
            Wearable("Berry Ski Jacket", "Clothing", "Special Power Up", 2, "a/aa/S2_Gear_Clothing_Berry_Ski_Jacket.png"),
            Wearable("Birded Corduroy Jacket", "Clothing", "Run Speed Up", 3, "7/74/S2_Gear_Clothing_Birded_Corduroy_Jacket.png"),
            Wearable("Black 8-Bit FishFry", "Clothing", "Bomb Defense Up DX", 1, "b/b7/S2_Gear_Clothing_Black_8-Bit_FishFry.png"),
            Wearable("Black Anchor Tee", "Clothing", "Respawn Punisher", 2, "f/f1/S2_Gear_Clothing_Black_Anchor_Tee.png"),
            Wearable("Black Baseball LS", "Clothing", "Swim Speed Up", 1, "3/3d/S2_Gear_Clothing_Black_Baseball_LS.png"),
            Wearable("Black Cuttlegear LS", "Clothing", "Swim Speed Up", 2, "c/c2/S2_Gear_Clothing_Black_Cuttlegear_LS.png"),
            Wearable("Black Hoodie", "Clothing", "Ink Resistance Up", 2, "7/73/S2_Gear_Clothing_Black_Hoodie.png"),
            Wearable("Black Inky Rider", "Clothing", "Sub Power Up", 3, "f/f5/S2_Gear_Clothing_Black_Inky_Rider.png"),
            Wearable("Black Layered LS", "Clothing", "Ink Saver (Main)", 1, "f/fa/S2_Gear_Clothing_Black_Layered_LS.png"),
            Wearable("Black LS", "Clothing", "Quick Super Jump", 2, "2/2b/S2_Gear_Clothing_Black_LS.png"),
            Wearable("Black Polo", "Clothing", "Ninja Squid", 1, "1/18/S2_Gear_Clothing_Black_Polo.png"),
            Wearable("Black Squideye", "Clothing", "Run Speed Up", 1, "c/cd/S2_Gear_Clothing_Black_Squideye.png"),
            Wearable("Black Tee", "Clothing", "Special Power Up", 1, "7/78/S2_Gear_Clothing_Black_Tee.png"),
            Wearable("Black Urchin Rock Tee", "Clothing", "Ink Recovery Up", 1, "0/00/S2_Gear_Clothing_Black_Urchin_Rock_Tee.png"),
            Wearable("Black V-Neck Tee", "Clothing", "Thermal Ink", 2, "e/eb/S2_Gear_Clothing_Black_V-Neck_Tee.png"),
            Wearable("Black Velour Octoking Tee", "Clothing", "Main Power Up", 2, "2/23/S2_Gear_Clothing_Black_Velour_Octoking_Tee.png"),
            Wearable("Blue 16-Bit FishFry", "Clothing", "Special Saver", 2, "0/0e/S2_Gear_Clothing_Blue_16-Bit_FishFry.png"),
            Wearable("Blue Peaks Tee", "Clothing", "Ink Saver (Sub)", 1, "e/e4/S2_Gear_Clothing_Blue_Peaks_Tee.png"),
            Wearable("Blue Sailor Suit", "Clothing", "Sub Power Up", 3, "6/6c/S2_Gear_Clothing_Blue_Sailor_Suit.png"),
            Wearable("Blue Tentatek Tee", "Clothing", "Quick Respawn", 2, "a/a8/S2_Gear_Clothing_Blue_Tentatek_Tee.png"),
            Wearable("Brown FA-11 Bomber", "Clothing", "Bomb Defense Up DX", 2, "2/21/S2_Gear_Clothing_Brown_FA-11_Bomber.png"),
            Wearable("Camo Layered LS", "Clothing", "Special Charge Up", 1, "5/56/S2_Gear_Clothing_Camo_Layered_LS.png"),
            Wearable("Camo Zip Hoodie", "Clothing", "Quick Respawn", 3, "6/62/S2_Gear_Clothing_Camo_Zip_Hoodie.png"),
            Wearable("Carnivore Tee", "Clothing", "Bomb Defense Up DX", 1, "5/5e/S2_Gear_Clothing_Carnivore_Tee.png"),
            Wearable("Chili Octo Aloha", "Clothing", "Bomb Defense Up DX", 2, "c/ce/S2_Gear_Clothing_Chili_Octo_Aloha.png"),
            Wearable("Chili-Pepper Ski Jacket", "Clothing", "Ink Resistance Up", 3, "9/94/S2_Gear_Clothing_Chili-Pepper_Ski_Jacket.png"),
            Wearable("Chilly Mountain Coat", "Clothing", "Swim Speed Up", 3, "c/c3/S2_Gear_Clothing_Chilly_Mountain_Coat.png"),
            Wearable("Chirpy Chirps Band Tee", "Clothing", "Main Power Up", 1, "d/df/S2_Gear_Clothing_Chirpy_Chips_Band_Tee.png"),
            Wearable("Choco Layered LS", "Clothing", "Ink Saver (Sub)", 1, "8/83/S2_Gear_Clothing_Choco_Layered_LS.png"),
            Wearable("Crimson Parashooter", "Clothing", "Special Charge Up", 3, "6/61/S2_Gear_Clothing_Crimson_Parashooter.png"),
            Wearable("Crustwear XXL", "Clothing", "Random", 3, "c/c8/S2_Gear_Clothing_Crustwear_XXL.png"),
            Wearable("Custom Painted F-3", "Clothing", "Ink Resistance Up", 3, "9/99/S2_Gear_Clothing_Custom_Painted_F-3.png"),
            Wearable("Cycle King Jersey", "Clothing", "Bomb Defense Up DX", 3, "0/0f/S2_Gear_Clothing_Cycle_King_Jersey.png"),
            Wearable("Cycling Shirt", "Clothing", "Main Power Up", 2, "c/c1/S2_Gear_Clothing_Cycling_Shirt.png"),
            Wearable("Dakro Golden Tee", "Clothing", "Thermal Ink", 1, "6/6e/S2_Gear_Clothing_Dakro_Golden_Tee.png"),
            Wearable("Dakro Nana Tee", "Clothing", "Quick Respawn", 1, "5/5f/S2_Gear_Clothing_Dakro_Nana_Tee.png"),
            Wearable("Dark Bomber Jacket", "Clothing", "Special Power Up", 3, "b/bf/S2_Gear_Clothing_Dark_Bomber_Jacket.png"),
            Wearable("Dark Urban Vest", "Clothing", "Main Power Up", 3, "2/2d/S2_Gear_Clothing_Dark_Urban_Vest.png"),
            Wearable("Deep-Octo Satin Jacket", "Clothing", "Main Power Up", 3, "0/08/S2_Gear_Clothing_Deep-Octo_Satin_Jacket.png"),
            Wearable("Dev Uniform", "Clothing", "Random", 3, "0/0f/S2_Gear_Clothing_Dev_Uniform.png"),
            Wearable("Dots-On-Dots Shirt", "Clothing", "Quick Super Jump", 3, "1/1b/S2_Gear_Clothing_Dots-On-Dots_Shirt.png"),
            Wearable("Enchanted Robe", "Clothing", "Thermal Ink", 2, "9/9b/S2_Gear_Clothing_Enchanted_Robe.png"),
            Wearable("Eggplant Mountain Coat", "Clothing", "Special Saver", 3, "0/0a/S2_Gear_Clothing_Eggplant_Mountain_Coat.png"),
            Wearable("FA-01 Jacket", "Clothing", "Ink Recovery Up", 3, "b/b3/S2_Gear_Clothing_FA-01_Jacket.png"),
            Wearable("FA-01 Reversed", "Clothing", "Quick Super Jump", 3, "4/4f/S2_Gear_Clothing_FA-01_Reversed.png"),
            Wearable("FC Albacore", "Clothing", "Respawn Punisher", 1, "2/28/S2_Gear_Clothing_FC_Albacore.png"),
            Wearable("Firefin Navy Sweat", "Clothing", "Sub Power Up", 2, "6/69/S2_Gear_Clothing_Firefin_Navy_Sweat.png"),
            Wearable("Firewave Tee", "Clothing", "Special Charge Up", 1, "7/70/S2_Gear_Clothing_Firewave_Tee.png"),
            Wearable("Fishing Vest", "Clothing", "Quick Respawn", 2, "7/79/S2_Gear_Clothing_Fishing_Vest.png"),
            Wearable("Forest Vest", "Clothing", "Ink Recovery Up", 3, "e/e9/S2_Gear_Clothing_Forest_Vest.png"),
            Wearable("Forge Inkling Parka", "Clothing", "Run Speed Up", 2, "e/e2/S2_Gear_Clothing_Forge_Inkling_Parka.png"),
            Wearable("Forge Octarian Jacket", "Clothing", "Haunt", 2, "f/f6/S2_Gear_Clothing_Forge_Octarian_Jacket.png"),
            Wearable("Fresh Fish Gloves", "Clothing", "Quick Super Jump", 2, "9/99/S2_Gear_Clothing_Fresh_Fish_Gloves.png"),
            Wearable("Fresh Octo Tee", "Clothing", "Ink Saver (Sub)", 1, "e/ed/S2_Gear_Clothing_Fresh_Octo_Tee.png"),
            Wearable("Friend Tee", "Clothing", "Thermal Ink", 1, "f/fb/S2_Gear_Clothing_Friend_Tee.png"),
            Wearable("Front Zip Vest", "Clothing", "Ink Resistance Up", 2, "b/bb/S2_Gear_Clothing_Front_Zip_Vest.png"),
            Wearable("Fugu Tee", "Clothing", "Swim Speed Up", 1, "5/5b/S2_Gear_Clothing_Fugu_Tee.png"),
            Wearable("Garden Gear", "Clothing", "Random", 3, "d/da/S2_Gear_Clothing_Garden_Gear.png"),
            Wearable("Grape Hoodie", "Clothing", "Quick Respawn", 1, "3/38/S2_Gear_Clothing_Grape_Hoodie.png"),
            Wearable("Grape Tee", "Clothing", "Ink Recovery Up", 1, "4/45/S2_Gear_Clothing_Grape_Tee.png8/8e/S2_Gear_Clothing_Gray_8-Bit_FishFry.png"),
            Wearable("Gray 8-Bit FishFry", "Clothing", "Special Charge Up", 1, "8/8e/S2_Gear_Clothing_Gray_8-Bit_FishFry.png"),
            Wearable("Gray College Sweat", "Clothing", "Swim Speed Up", 1, "8/81/S2_Gear_Clothing_Gray_College_Sweat.png"),
            Wearable("Gray FA-11 Bomber", "Clothing", "Bomb Defense Up DX", 2, "a/a0/S2_Gear_Clothing_Gray_FA-11_Bomber.png"),
            Wearable("Gray Hoodie", "Clothing", "Sub Power Up", 2, "e/e2/S2_Gear_Clothing_Gray_Hoodie.png"),
            Wearable("Gray Mixed Shirt", "Clothing", "Quick Super Jump", 2, "f/f4/S2_Gear_Clothing_Gray_Mixed_Shirt.png"),
            Wearable("Gray Vector Tee", "Clothing", "Quick Super Jump", 1, "c/ca/S2_Gear_Clothing_Gray_Vector_Tee.png"),
            Wearable("Green Cardigan", "Clothing", "Ink Saver (Sub)", 2, "8/82/S2_Gear_Clothing_Green_Cardigan.png"),
            Wearable("Green Striped LS", "Clothing", "Ninja Squid", 1, "0/07/S2_Gear_Clothing_Green_Striped_LS.png"),
            Wearable("Green Tee", "Clothing", "Special Saver", 1, "1/14/S2_Gear_Clothing_Green_Tee.png"),
            Wearable("Green V-Neck Limited Tee", "Clothing", "Quick Super Jump", 2, "b/b3/S2_Gear_Clothing_Green_V-Neck_Limited_Tee.png"),
            Wearable("Green Velour Octoking Tee", "Clothing", "Special Saver", 1, "7/70/S2_Gear_Clothing_Green_Velour_Octoking_Tee.png"),
            Wearable("Green Zip Hoodie", "Clothing", "Special Power Up", 2, "1/1b/S2_Gear_Clothing_Green_Zip_Hoodie.png"),
            Wearable("Green-Check Shirt", "Clothing", "Sub Power Up", 2, "8/86/S2_Gear_Clothing_Green-Check_Shirt.png"),
            Wearable("Half-Sleeve Sweater", "Clothing", "Ink Saver (Sub)", 2, "4/41/S2_Gear_Clothing_Half-Sleeve_Sweater.png"),
            Wearable("Herbivore Tee", "Clothing", "Ninja Squid", 1, "2/2b/S2_Gear_Clothing_Herbivore_Tee.png"),
            Wearable("Hero Hoodie Replica", "Clothing", "Ink Recovery Up", 2, "2/2a/S2_Gear_Clothing_Hero_Hoodie_Replica.png"),
            Wearable("Hero Jacket Replica", "Clothing", "Swim Speed Up", 2, "b/b2/S2_Gear_Clothing_Hero_Jacket_Replica.png"),
            Wearable("Hightide Era Brand Tee", "Clothing", "Thermal Ink", 1, "b/bb/S2_Gear_Clothing_Hightide_Era_Band_Tee.png"),
            Wearable("Hothouse Hoodie", "Clothing", "Run Speed Up", 2, "e/eb/S2_Gear_Clothing_Hothouse_Hoodie.png"),
            Wearable("Hula Punk Shirt", "Clothing", "Ink Saver (Main)", 2, "8/86/S2_Gear_Clothing_Hula_Punk_Shirt.png"),
            Wearable("Icewave Tee", "Clothing", "Ninja Squid", 1, "4/49/S2_Gear_Clothing_Icewave_Tee.png"),
            Wearable("Ink-Wash Shirt", "Clothing", "Ink Recovery Up", 2, "0/08/S2_Gear_Clothing_Ink-Wash_Shirt.png"),
            Wearable("Inkfall Shirt", "Clothing", "Special Charge Up", 2, "3/3f/S2_Gear_Clothing_Inkfall_Shirt.png"),
            Wearable("Inkopolis Squaps Jersey", "Clothing", "Main Power Up", 1, "a/a4/S2_Gear_Clothing_Inkopolis_Squaps_Jersey.png"),
            Wearable("Ivory Peaks Tee", "Clothing", "Haunt", 1, "3/3f/S2_Gear_Clothing_Ivory_Peaks_Tee.png"),
            Wearable("Juice Parka", "Clothing", "Random", 3, "e/e8/S2_Gear_Clothing_Juice_Parka.png"),
            Wearable("Kensa Coat", "Clothing", "Respawn Punisher", 3, "9/99/S2_Gear_Clothing_Kensa_Coat.png"),
            Wearable("Khaki 16-Bit FishFry", "Clothing", "Ink Recovery Up", 2, "b/bd/S2_Gear_Clothing_Khaki_16-Bit_FishFry.png"),
            Wearable("King Jersey", "Clothing", "Respawn Punisher", 2, "a/a8/S2_Gear_Clothing_King_Jersey.png"),
            Wearable("Krak-On 528", "Clothing", "Run Speed Up", 1, "f/f1/S2_Gear_Clothing_Krak-On_528.png"),
            Wearable("Kung-Fu Zip-Up", "Clothing", "Ninja Squid", 3, "3/37/S2_Gear_Clothing_Kung-Fu_Zip-Up.png"),
            Wearable("Layered Anchor LS", "Clothing", "Run Speed Up", 2, "b/bd/S2_Gear_Clothing_Layered_Anchor_LS.png"),
            Wearable("Layered Vector LS", "Clothing", "Special Saver", 1, "1/17/S2_Gear_Clothing_Layered_Vector_LS.png"),
            Wearable("League Tee", "Clothing", "Special Power Up", 2, "6/6a/S2_Gear_Clothing_League_Tee.png"),
            Wearable("Light Bomber Jacket", "Clothing", "Quick Super Jump", 3, "c/cd/S2_Gear_Clothing_Light_Bomber_Jacket.png"),
            Wearable("Lime Easy-Stripe Shirt", "Clothing", "Ink Resistance Up", 2, "9/98/S2_Gear_Clothing_Lime_Easy-Stripe_Shirt.png"),
            Wearable("Linen Shirt", "Clothing", "Sub Power Up", 1, "3/35/S2_Gear_Clothing_Linen_Shirt.png"),
            Wearable("Lob-Stars Jersey", "Clothing", "Sub Power Up", 2, "6/6c/S2_Gear_Clothing_Lob-Stars_Jersey.png"),
            Wearable("Logo Aloha Shirt", "Clothing", "Ink Recovery Up", 2, "7/7a/S2_Gear_Clothing_Logo_Aloha_Shirt.png"),
            Wearable("Lumberjack Shirt", "Clothing", "Ink Saver (Main)", 1, "7/76/S2_Gear_Clothing_Lumberjack_Shirt.png"),
            Wearable("Marinated Top", "Clothing", "Special Power Up", 2, "9/92/S2_Gear_Clothing_Marinated_Top.png"),
            Wearable("Matcha Down Jacket", "Clothing", "Ninja Squid", 3, "0/0e/S2_Gear_Clothing_Matcha_Down_Jacket.png"),
            Wearable("Mecha Body AKM", "Clothing", "Sub Power Up", 3, "9/93/S2_Gear_Clothing_Mecha_Body_-_AKM.png"),
            Wearable("Milky Eminence Jacket", "Clothing", "Run Speed Up", 3, "a/ac/S2_Gear_Clothing_Milky_Eminence_Jacket.png"),
            Wearable("Mint Tee", "Clothing", "Bomb Defense Up DX", 1, "4/4b/S2_Gear_Clothing_Mint_Tee.png"),
            Wearable("Missus Shrug Tee", "Clothing", "Ink Saver (Sub)", 3, "0/0b/S2_Gear_Clothing_Missus_Shrug_Tee.png"),
            Wearable("Mister Shrug Tee", "Clothing", "Ink Resistance Up", 3, "5/51/S2_Gear_Clothing_Mister_Shrug_Tee.png"),
            Wearable("Moist Ghillie Suit", "Clothing", "Ink Saver (Sub)", 3, "f/f9/S2_Gear_Clothing_Moist_Ghillie_Suit.png"),
            Wearable("Mountain Vest", "Clothing", "Swim Speed Up", 3, "e/ef/S2_Gear_Clothing_Mountain_Vest.png"),
            Wearable("N-Pacer Sweat", "Clothing", "Thermal Ink", 3, "1/18/S2_Gear_Clothing_N-Pacer_Sweat.png"),
            Wearable("Navy College Sweat", "Clothing", "Ink Resistance Up", 1, "6/64/S2_Gear_Clothing_Navy_College_Sweat.png"),
            Wearable("Navy Deca Logo Tee", "Clothing", "Ink Saver (Main)", 1, "4/4e/S2_Gear_Clothing_Navy_Deca_Logo_Tee.png"),
            Wearable("Navy Eminence Jacket", "Clothing", "Ink Saver (Main)", 3, "6/64/S2_Gear_Clothing_Navy_Eminence_Jacket.png"),
            Wearable("Navy King Tank", "Clothing", "Ink Resistance Up", 1, "5/51/S2_Gear_Clothing_Navy_King_Tank.png"),
            Wearable("Navy Striped LS", "Clothing", "Ink Recovery Up", 1, "d/db/S2_Gear_Clothing_Navy_Striped_LS.png"),
            Wearable("Negative Longcuff Sweater", "Clothing", "Haunt", 3, "0/09/S2_Gear_Clothing_Negative_Longcuff_Sweater.png"),
            Wearable("Neo Octoling Armor", "Clothing", "Haunt", 2, "5/57/S2_Gear_Clothing_Neo_Octoling_Armor.png"),
            Wearable("North Country Parka", "Clothing", "Random", 3, "7/79/S2_Gear_Clothing_North-Country_Parka.png"),
            Wearable("Null Armor Replica", "Clothing", "Ink Resistance Up", 2, "e/ef/S2_Gear_Clothing_Null_Armor_Replica.png"),
            Wearable("Octarian Retro", "Clothing", "Respawn Punisher", 2, "6/63/S2_Gear_Clothing_Octarian_Retro.png"),
            Wearable("Octo Layered LS", "Clothing", "Ink Saver (Main)", 3, "5/53/S2_Gear_Clothing_Octo_Layered_LS.png"),
            Wearable("Octo Support Hoodie", "Clothing", "Main Power Up", 3, "1/16/S2_Gear_Clothing_Octo_Support_Hoodie.png"),
            Wearable("Octo Tee", "Clothing", "Haunt", 3, "7/7a/S2_Gear_Clothing_Octo_Tee.png"),
            Wearable("Octobowler Shirt", "Clothing", "Ink Saver (Main)", 2, "8/8e/S2_Gear_Clothing_Octobowler_Shirt.png"),
            Wearable("Octoking HK Jersey", "Clothing", "Special Charge Up", 2, "5/58/S2_Gear_Clothing_Octoking_HK_Jersey.png"),
            Wearable("Office Attire", "Clothing", "Random", 3, "e/eb/S2_Gear_Clothing_Office_Attire.png"),
            Wearable("Old-Timey Clothes", "Clothing", "Thermal Ink", 2, "a/a1/S2_Gear_Clothing_Old-Timey_Clothes.png"),
            Wearable("Olive Ski Jacket", "Clothing", "Run Speed Up", 3, "9/95/S2_Gear_Clothing_Olive_Ski_Jacket.png"),
            Wearable("Olive Zekko Parka", "Clothing", "Swim Speed Up", 2, "f/ff/S2_Gear_Clothing_Olive_Zekko_Parka.png"),
            Wearable("Online Jersey", "Clothing", "Swim Speed Up", 3, "a/a1/S2_Gear_Clothing_Online_Jersey.png"),
            Wearable("Orange Cardigan", "Clothing", "Special Charge Up", 1, "0/0f/S2_Gear_Clothing_Orange_Cardigan.png"),
            Wearable("Panda Kung-Fu Zip-Up", "Clothing", "Sub Power Up", 3, "1/1d/S2_Gear_Clothing_Panda_Kung-Fu_Zip-Up.png"),
            Wearable("Part-Time Pirate", "Clothing", "Respawn Punisher", 1, "c/cb/S2_Gear_Clothing_Part-Time_Pirate.png"),
            Wearable("Pearl Tee", "Clothing", "Ink Saver (Sub)", 1, "e/ee/S2_Gear_Clothing_Pearl_Tee.png"),
            Wearable("Pearlescent Hoodie", "Clothing", "Respawn Punisher", 2, "b/b7/S2_Gear_Clothing_Pearlescent_Hoodie.png"),
            Wearable("Pink Easy-Stripe Shirt", "Clothing", "Quick Super Jump", 2, "a/a3/S2_Gear_Clothing_Pink_Easy-Stripe_Shirt.png"),
            Wearable("Pink Hoodie", "Clothing", "Bomb Defense Up DX", 2, "7/77/S2_Gear_Clothing_Pink_Hoodie.png7/76/S2_Gear_Clothing_Pirate-Stripe_Tee.png"),
            Wearable("Pirate-Stripe Tee", "Clothing", "Special Power Up", 1, "7/76/S2_Gear_Clothing_Pirate-Stripe_Tee.png"),
            Wearable("Positive Longcuff Sweater", "Clothing", "Swim Speed Up", 3, "d/da/S2_Gear_Clothing_Positive_Longcuff_Sweater.png"),
            Wearable("Power Armor", "Clothing", "Quick Respawn", 2, "0/09/S2_Gear_Clothing_Power_Armor.png"),
            Wearable("Power Armor Mk I", "Clothing", "Ink Resistance Up", 2, "5/54/S2_Gear_Clothing_Power_Armor_Mk_I.png"),
            Wearable("Prune Parashooter", "Clothing", "Ninja Squid", 3, "6/6b/S2_Gear_Clothing_Prune_Parashooter.png"),
            Wearable("Pullover Coat", "Clothing", "Thermal Ink", 3, "a/a0/S2_Gear_Clothing_Pullover_Coat.png"),
            Wearable("Purple Camo LS", "Clothing", "Sub Power Up", 1, "7/77/S2_Gear_Clothing_Purple_Camo_LS.png"),
            Wearable("Rainy-Day Tee", "Clothing", "Ink Saver (Main)", 1, "2/2f/S2_Gear_Clothing_Rainy-Day_Tee.png"),
            Wearable("Record Shop Look EP", "Clothing", "Random", 3, "3/3f/S2_Gear_Clothing_Record_Shop_Look_EP.png"),
            Wearable("Red Cuttlegear LS", "Clothing", "Bomb Defense Up DX", 2, "a/ab/S2_Gear_Clothing_Red_Cuttlegear_LS.png"),
            Wearable("Red Hula Punk with Tie", "Clothing", "Ink Resistance Up", 3, "f/f8/S2_Gear_Clothing_Red_Hula_Punk_with_Tie.png"),
            Wearable("Red Tentatek Tee", "Clothing", "Swim Speed Up", 2, "c/c0/S2_Gear_Clothing_Red_Tentatek_Tee.png"),
            Wearable("Red V-Neck Limited Tee", "Clothing", "Quick Respawn", 2, "9/96/S2_Gear_Clothing_Red_V-Neck_Limited_Tee.png"),
            Wearable("Red Vector Tee", "Clothing", "Ink Saver (Main)", 1, "d/dc/S2_Gear_Clothing_Red_Vector_Tee.png"),
            Wearable("Red-Check Shirt", "Clothing", "Ink Saver (Main)", 2, "2/21/S2_Gear_Clothing_Red-Check_Shirt.png"),
            Wearable("Reel Sweat", "Clothing", "Special Power Up", 1, "2/22/S2_Gear_Clothing_Reel_Sweat.png"),
            Wearable("Reggae Tee", "Clothing", "Special Saver", 3, "a/a2/S2_Gear_Clothing_Reggae_Tee.png"),
            Wearable("Retro Gamer Jersey", "Clothing", "Quick Respawn", 3, "1/14/S2_Gear_Clothing_Retro_Gamer_Jersey.png"),
            Wearable("Retro Sweat", "Clothing", "Bomb Defense Up DX", 3, "5/56/S2_Gear_Clothing_Retro_Sweat.png"),
            Wearable("Rockenberg Black", "Clothing", "Respawn Punisher", 1, "b/b0/S2_Gear_Clothing_Rockenberg_Black.png"),
            Wearable("Rockenberg White", "Clothing", "Ink Recovery Up", 2, "9/92/S2_Gear_Clothing_Rockenberg_White.png"),
            Wearable("Rockin' Leather Jacket", "Clothing", "Sub Power Up", 3, "3/3c/S2_Gear_Clothing_Rockin%27_Leather_Jacket.png"),
            Wearable("Rodeo Shirt", "Clothing", "Quick Super Jump", 1, "e/ea/S2_Gear_Clothing_Rodeo_Shirt.png"),
            Wearable("Round-Collar Shirt", "Clothing", "Ink Saver (Sub)", 2, "d/d3/S2_Gear_Clothing_Round-Collar_Shirt.png"),
            Wearable("Sage Polo", "Clothing", "Main Power Up", 1, "8/82/S2_Gear_Clothing_Sage_Polo.png"),
            Wearable("Sailor-Stripe Tee", "Clothing", "Run Speed Up", 1, "1/1e/S2_Gear_Clothing_Sailor-Stripe_Tee.png"),
            Wearable("Samurai Jacket", "Clothing", "Special Charge Up", 2, "3/32/S2_Gear_Clothing_Samurai_Jacket.png"),
            Wearable("School Cardigan", "Clothing", "Run Speed Up", 2, "e/ee/S2_Gear_Clothing_School_Cardigan.png"),
            Wearable("School Jersey", "Clothing", "Ninja Squid", 2, "d/d4/S2_Gear_Clothing_School_Jersey.png"),
            Wearable("School Uniform", "Clothing", "Ink Recovery Up", 2, "0/05/S2_Gear_Clothing_School_Uniform.png"),
            Wearable("Sennyu Suit", "Clothing", "Ninja Squid", 3, "7/74/S2_Gear_Clothing_Sennyu_Suit.png"),
            Wearable("Shirt & Tie", "Clothing", "Special Saver", 3, "b/b6/S2_Gear_Clothing_Shirt_%26_Tie.png"),
            Wearable("Shirt with Blue Hoodie", "Clothing", "Special Power Up", 2, "9/9e/S2_Gear_Clothing_Shirt_with_Blue_Hoodie.png"),
            Wearable("Short Knit Layers", "Clothing", "Ink Saver (Main)", 3, "5/54/S2_Gear_Clothing_Short_Knit_Layers.png"),
            Wearable("Shrimp-Pink Polo", "Clothing", "Ninja Squid", 1, "3/3d/S2_Gear_Clothing_Shrimp-Pink_Polo.png"),
            Wearable("Silver Tentatek Vest", "Clothing", "Thermal Ink", 2, "0/0e/S2_Gear_Clothing_Silver_Tentatek_Vest.png"),
            Wearable("Sky-Blue Squideye", "Clothing", "Main Power Up", 1, "f/f3/S2_Gear_Clothing_Sky-Blue_Squideye.png"),
            Wearable("Slash King Tank", "Clothing", "Thermal Ink", 1, "7/72/S2_Gear_Clothing_Slash_King_Tank.png"),
            Wearable("Slipstream United", "Clothing", "Bomb Defense Up DX", 2, "4/47/S2_Gear_Clothing_Slipstream_United.png"),
            Wearable("Splatfest Tee", "Clothing", "Ability Doubler", 3, "8/8d/S2_Gear_Clothing_Splatfest_Tee.png"),
            Wearable("Splatfest Tee Replica", "Clothing", "Ability Doubler", 3, "8/8c/S2_Gear_Clothing_Splatfest_Tee_Replica.png"),
            Wearable("Squid Satin Jacket", "Clothing", "Quick Respawn", 3, "d/d0/S2_Gear_Clothing_Squid_Satin_Jacket.png"),
            Wearable("Squid Squad Band Tee", "Clothing", "Ink Resistance Up", 1, "f/f4/S2_Gear_Clothing_Squid_Squad_Band_Tee.png"),
            Wearable("Squid Yellow Layered LS", "Clothing", "Swim Speed Up", 2, "a/af/S2_Gear_Clothing_Squid_Yellow_Layered_LS.png"),
            Wearable("Squid-Pattern Waistcoat", "Clothing", "Special Power Up", 1, "a/a3/S2_Gear_Clothing_Squid-Pattern_Waistcoat.png"),
            Wearable("Squid-Stitch Tee", "Clothing", "Swim Speed Up", 1, "8/89/S2_Gear_Clothing_Squid-Stitch_Tee.png"),
            Wearable("Squiddor Polo", "Clothing", "Random", 3, "7/78/S2_Gear_Clothing_Squiddor_Polo.png"),
            Wearable("Squidmark LS", "Clothing", "Haunt", 1, "fd/S2_Gear_Clothing_Squidmark_LS.png"),
            Wearable("Squidmark Sweat", "Clothing", "Sub Power Up", 1, "c/cf/S2_Gear_Clothing_Squidmark_Sweat.png"),
            Wearable("Squidstar Waistcoat", "Clothing", "Main Power Up", 1, "0/04/S2_Gear_Clothing_Squidstar_Waistcoat.png"),
            Wearable("Squinja Suit", "Clothing", "Special Saver", 2, "c/ce/S2_Gear_Clothing_Squinja_Suit.png"),
            Wearable("SRL Coat", "Clothing", "Random", 3, "c/c3/S2_Gear_Clothing_SRL_Coat.png"),
            Wearable("Steel Platemail", "Clothing", "Ink Saver (Sub)", 2, "d/d0/S2_Gear_Clothing_Steel_Platemail.png"),
            Wearable("Striped Peaks LS", "Clothing", "Quick Super Jump", 1, "d/dd/S2_Gear_Clothing_Striped_Peaks_LS.png"),
            Wearable("Striped Rugby", "Clothing", "Run Speed Up", 2, "9/9f/S2_Gear_Clothing_Striped_Rugby.png"),
            Wearable("Striped Shirt", "Clothing", "Quick Super Jump", 2, "1/1d/S2_Gear_Clothing_Striped_Shirt.png"),
            Wearable("Sunny-Day Tee", "Clothing", "Special Charge Up", 1, "3/32/S2_Gear_Clothing_Sunny-Day_Tee.png"),
            Wearable("SWC Logo Tee", "Clothing", "Swim Speed Up", 3, "7/7f/S2_Gear_Clothing_SWC_Logo_Tee.png"),
            Wearable("Takoroka Crazy Baseball LS", "Clothing", "Ninja Squid", 2, "e/ef/S2_Gear_Clothing_Takoroka_Crazy_Baseball_LS.png"),
            Wearable("Takoroka Galactic Tie Dye", "Clothing", "Thermal Ink", 1, "4/43/S2_Gear_Clothing_Takoroka_Galactic_Tie_Dye.png"),
            Wearable("Takoroka Jersey", "Clothing", "Special Power Up", 3, "a/ab/S2_Gear_Clothing_Takoroka_Jersey.png"),
            Wearable("Takoroka Nylon Vintage", "Clothing", "Thermal Ink", 3, "2/2c/S2_Gear_Clothing_Takoroka_Nylon_Vintage.png"),
            Wearable("Takoroka Rainbow Tie Dye", "Clothing", "Quick Super Jump", 1, "6/6e/S2_Gear_Clothing_Takoroka_Rainbow_Tie_Dye.png"),
            Wearable("Takoroka Windcrusher", "Clothing", "Main Power Up", 3, "6/62/S2_Gear_Clothing_Takoroka_Windcrusher.png"),
            Wearable("Tentatek Slogan Tee", "Clothing", "Special Charge Up", 2, "b/b2/S2_Gear_Clothing_Tentatek_Slogan_Tee.png"),
            Wearable("Toni K. Baseball Jersey", "Clothing", "Special Charge Up", 3, "1/13/S2_Gear_Clothing_Toni_K._Baseball_Jersey.png"),
            Wearable("Tricolor Rugby", "Clothing", "Quick Respawn", 1, "e/ef/S2_Gear_Clothing_Tricolor_Rugby.png"),
            Wearable("Tumeric Zekko Coat", "Clothing", "Thermal Ink", 2, "c/c9/S2_Gear_Clothing_Tumeric_Zekko_Coat.png"),
            Wearable("Urchins Jersey", "Clothing", "Run Speed Up", 1, "3/31/S2_Gear_Clothing_Urchins_Jersey.png"),
            Wearable("Varsity Baseball LS", "Clothing", "Haunt", 1, "4/4e/S2_Gear_Clothing_Varsity_Baseball_LS.png"),
            Wearable("Varsity Jacket", "Clothing", "Ink Saver (Sub)", 3, "e/eb/S2_Gear_Clothing_Varsity_Jacket.png"),
            Wearable("Vintage Check Shirt", "Clothing", "Haunt", 3, "6/65/S2_Gear_Clothing_Vintage_Check_Shirt.png"),
            Wearable("Wet Floor Band Tee", "Clothing", "Swim Speed Up", 1, "d/d4/S2_Gear_Clothing_Wet_Floor_Band_Tee.png"),
            Wearable("Whale-Knit Sweater", "Clothing", "Run Speed Up", 3, "7/78/S2_Gear_Clothing_Whale-Knit_Sweater.png"),
            Wearable("White 8-Bit FishFry", "Clothing", "Sub Power Up", 1, "2/2f/S2_Gear_Clothing_White_8-Bit_FishFry.png"),
            Wearable("White Anchor Tee", "Clothing", "Ninja Squid", 2, "3/3e/S2_Gear_Clothing_White_Anchor_Tee.png"),
            Wearable("White Baseball LS", "Clothing", "Quick Super Jump", 1, "9/9c/S2_Gear_Clothing_White_Baseball_LS.png"),
            Wearable("White Deca Logo Tee", "Clothing", "Ink Resistance Up", 1, "e/eb/S2_Gear_Clothing_White_Deca_Logo_Tee.png"),
            Wearable("White Inky Rider", "Clothing", "Special Power Up", 3, "f/f2/S2_Gear_Clothing_White_Inky_Rider.png"),
            Wearable("White King Tank", "Clothing", "Haunt", 1, "4/44/S2_Gear_Clothing_White_King_Tank.png"),
            Wearable("White Layered LS", "Clothing", "Special Saver", 1, "1/13/S2_Gear_Clothing_White_Layered_LS.png"),
            Wearable("White Leather F-3", "Clothing", "Respawn Punisher", 3, "4/49/S2_Gear_Clothing_White_Leather_F-3.png"),
            Wearable("White LS", "Clothing", "Ink Recovery Up", 1, "5/5d/S2_Gear_Clothing_White_LS.png"),
            Wearable("White Sailor Suit", "Clothing", "Ink Saver (Main)", 2, "7/7e/S2_Gear_Clothing_White_Sailor_Suit.png"),
            Wearable("White Shirt", "Clothing", "Ink Recovery Up", 3, "c/c1/S2_Gear_Clothing_White_Shirt.png"),
            Wearable("White Striped LS", "Clothing", "Quick Respawn", 2, "1/1f/S2_Gear_Clothing_White_Striped_LS.png"),
            Wearable("White Tee", "Clothing", "Ink Saver (Sub)", 1, "8/80/S2_Gear_Clothing_White_Tee.png"),
            Wearable("White Urchin Rock Tee", "Clothing", "Ink Saver (Main)", 1, "d/dd/S2_Gear_Clothing_White_Urchin_Rock_Tee.png"),
            Wearable("White V-Neck Tee", "Clothing", "Special Saver", 2, "5/55/S2_Gear_Clothing_White_V-Neck_Tee.png"),
            Wearable("Yellow Layered LS", "Clothing", "Quick Super Jump", 1, "c/c2/S2_Gear_Clothing_Yellow_Layered_LS.png"),
            Wearable("Yellow Urban Vest", "Clothing", "Haunt", 2, "e/e9/S2_Gear_Clothing_Yellow_Urban_Vest.png"),
            Wearable("Zapfish Satin Jacket", "Clothing", "Special Charge Up", 2, "6/6a/S2_Gear_Clothing_Zapfish_Satin_Jacket.png"),
            Wearable("Zekko Baseball LS", "Clothing", "Bomb Defense Up DX", 1, "d/d1/S2_Gear_Clothing_Zekko_Baseball_LS.png"),
            Wearable("Zekko Hoodie", "Clothing", "Ninja Squid", 2, "e/e5/S2_Gear_Clothing_Zekko_Hoodie.png"),
            Wearable("Zekko Jade Coat", "Clothing", "Respawn Punisher", 2, "4/46/S2_Gear_Clothing_Zekko_Jade_Coat.png"),
            Wearable("Zekko Long Carrot Tee", "Clothing", "Ink Resistance Up", 2, "d/d7/S2_Gear_Clothing_Zekko_Long_Carrot_Tee.png"),
            Wearable("Zekko Long Radish Tee", "Clothing", "Haunt", 1, "2/2b/S2_Gear_Clothing_Zekko_Long_Radish_Tee.png"),
            Wearable("Zekko Redleaf Coat", "Clothing", "Haunt", 2, "e/e9/S2_Gear_Clothing_Zekko_Redleaf_Coat.png"),
            Wearable("Zink Layered LS", "Clothing", "Respawn Punisher", 1, "c/c9/S2_Gear_Clothing_Zink_Layered_LS.png"),
            Wearable("Zink LS", "Clothing", "Special Power Up", 1, "d/dd/S2_Gear_Clothing_Zink_LS.png"),
            Wearable("ω-3 Tee", "Clothing", "Respawn Punisher", 1, "4/42/S2_Gear_Clothing_ω-3_Tee.png"),
            Wearable("Acerola Rain Boots", "Shoes", "Run Speed Up", 1, "4/47/S2_Gear_Shoes_Acerola_Rain_Boots.png"),
            Wearable("Amber Sea Slug Hi-Tops", "Shoes", "Drop Roller", 3, "4/4e/S2_Gear_Shoes_Amber_Sea_Slug_Hi-Tops.png"),
            Wearable("Angry Rain Boots", "Shoes", "Random", 3, "5/54/S2_Gear_Shoes_Angry_Rain_Boots.png"),
            Wearable("Annaki Arachno Boots", "Shoes", "Swim Speed Up", 3, "4/4e/S2_Gear_Shoes_Annaki_Arachno_Boots.png"),
            Wearable("Annaki Habaneros", "Shoes", "Sub Power Up", 3, "f/fc/S2_Gear_Shoes_Annaki_Habaneros.png"),
            Wearable("Annaki Tigers", "Shoes", "Special Power Up", 3, "5/54/S2_Gear_Shoes_Annaki_Tigers.png"),
            Wearable("Armor Boot Replicas", "Shoes", "Ink Saver (Main)", 2, "3/36/S2_Gear_Shoes_Armor_Boot_Replicas.png"),
            Wearable("Arrow Pull-Ons", "Shoes", "Drop Roller", 3, "1/11/S2_Gear_Shoes_Arrow_Pull-Ons.png"),
            Wearable("Athletic Arrows", "Shoes", "Object Shredder", 1, "e/ee/S2_Gear_Shoes_Athletic_Arrows.png"),
            Wearable("Banana Basics", "Shoes", "Bomb Defense Up DX", 1, "7/70/S2_Gear_Shoes_Banana_Basics.png"),
            Wearable("Birch Climbing Shoes", "Shoes", "Special Charge Up", 1, "e/e2/S2_Gear_Shoes_Birch_Climbing_Shoes.png"),
            Wearable("Black & Blue Squidkid V", "Shoes", "Special Saver Up", 3, "a/a7/S2_Gear_Shoes_Black_%26_Blue_Squidkid_V.png"),
            Wearable("Black Dakroniks", "Shoes", "Main Power Up", 2, "9/94/S2_Gear_Shoes_Black_Dakroniks.png"),
            Wearable("Black Flip-Flops", "Shoes", "Object Shredder", 1, "6/69/S2_Gear_Shoes_Black_Flip-Flops.png"),
            Wearable("Black Norimaki 750s", "Shoes", "Special Charge Up", 3, "6/6c/S2_Gear_Shoes_Black_Norimaki_750s.png"),
            Wearable("Black Seahorses", "Shoes", "Swim Speed Up", 2, "0/01/S2_Gear_Shoes_Black_Seahorses.png"),
            Wearable("Black Trainers", "Shoes", "Quick Respawn", 1, "f/f0/S2_Gear_Shoes_Black_Trainers.png"),
            Wearable("Blue & Black Squidkid IV", "Shoes", "Quick Super Jump", 3, "9/97/S2_Gear_Shoes_Blue_%26_Black_Squidkid_IV.png"),
            Wearable("Blue Iromaki 750s", "Shoes", "Ink Saver (Main)", 1, "0/07/S2_Gear_Shoes_Blue_Iromaki_750s.png"),
            Wearable("Blue Laceless Dakroniks", "Shoes", "Stealth Jump", 1, "0/00/S2_Gear_Shoes_Blue_Laceless_Dakroniks.png"),
            Wearable("Blue Lo-Tops", "Shoes", "Bomb Defense Up DX", 1, "c/c7/S2_Gear_Shoes_Blue_Lo-Tops.png"),
            Wearable("Blue Moto Boots", "Shoes", "Ink Resistance Up", 3, "4/4d/S2_Gear_Shoes_Blue_Moto_Boots.png"),
            Wearable("Blue Power Stripes", "Shoes", "Quick Respawn", 2, "2/23/S2_Gear_Shoes_Blue_Power_Stripes.png"),
            Wearable("Blue Sea Slugs", "Shoes", "Special Charge Up", 1, "b/b9/S2_Gear_Shoes_Blue_Sea_Slugs.png"),
            Wearable("Blue Slip-Ons", "Shoes", "Sub Power Up", 1, "0/08/S2_Gear_Shoes_Blue_Slip-Ons.png"),
            Wearable("Blueberry Casuals", "Shoes", "Ink Saver (Sub)", 1, "3/32/S2_Gear_Shoes_Blueberry_Casuals.png"),
            Wearable("Bubble Rain Boots", "Shoes", "Drop Roller", 1, "c/c9/S2_Gear_Shoes_Bubble_Rain_Boots.png"),
            Wearable("Canary Trainers", "Shoes", "Quick Super Jump", 1, "0/02/S2_Gear_Shoes_Canary_Trainers.png"),
            Wearable("Cherry Kicks", "Shoes", "Stealth Jump", 2, "e/e7/S2_Gear_Shoes_Cherry_Kicks.png"),
            Wearable("Choco Clogs", "Shoes", "Quick Respawn", 2, "b/b0/S2_Gear_Shoes_Choco_Clogs.png"),
            Wearable("Chocolate Dakroniks", "Shoes", "Ink Resistance Up", 2, "f/fd/S2_Gear_Shoes_Chocolate_Dakroniks.png"),
            Wearable("Clownfish Basics", "Shoes", "Special Charge Up", 1, "a/a1/S2_Gear_Shoes_Clownfish_Basics.png"),
            Wearable("Crazy Arrows", "Shoes", "Stealth Jump", 2, "7/72/S2_Gear_Shoes_Crazy_Arrows.png"),
            Wearable("Cream Basics", "Shoes", "Special Saver", 1, "1/1c/S2_Gear_Shoes_Cream_Basics.png"),
            Wearable("Cream Hi-Tops", "Shoes", "Stealth Jump", 1, "2/28/S2_Gear_Shoes_Cream_Hi-Tops.png"),
            Wearable("Custom Trail Boots", "Shoes", "Special Power Up", 2, "7/70/S2_Gear_Shoes_Custom_Trail_Boots.png"),
            Wearable("Cyan Trainers", "Shoes", "Stealth Jump", 1, "9/94/S2_Gear_Shoes_Cyan_Trainers.png"),
            Wearable("Deepsea Leather Boots", "Shoes", "Ink Saver (Sub)", 3, "2/28/S2_Gear_Shoes_Deepsea_Leather_Boots.png"),
            Wearable("Enchanted Boots", "Shoes", "Run Speed Up", 2, "images/b/b6/S2_Gear_Shoes_Enchanted_Boots.png"),
            Wearable("Flipper Floppers", "Shoes", "Random", 3, "7/73/S2_Gear_Shoes_Flipper_Floppers.png"),
            Wearable("Fresh Fish Feet", "Shoes", "Quick Respawn", 2, "e/e3/S2_Gear_Shoes_Fresh_Fish_Feet.png"),
            Wearable("Friendship Bracelet", "Shoes", "Random", 3, "c/c6/S2_Gear_Shoes_Friendship_Bracelet.png"),
            Wearable("Fringed Loafers", "Shoes", "Bomb Defense Up DX", 2, "2/29/S2_Gear_Shoes_Fringed_Loafers.png"),
            Wearable("Gold Hi-Horses", "Shoes", "Run Speed Up", 3, "a/ab/S2_Gear_Shoes_Gold_Hi-Horses.png"),
            Wearable("Gray Sea-Slug Hi-Tops", "Shoes", "Bomb Defense Up DX", 3, "8/8b/S2_Gear_Shoes_Gray_Sea-Slug_Hi-Tops.png"),
            Wearable("Gray Yellow-Soled Wingtips", "Shoes", "Quick Super Jump", 2, "9/92/S2_Gear_Shoes_Gray_Yellow-Soled_Wingtips.png"),
            Wearable("Green Iromaki 750s", "Shoes", "Special Power Up", 1, "0/03/S2_Gear_Shoes_Green_Iromaki_750s.png"),
            Wearable("Green Laceups", "Shoes", "Main Power Up", 1, "1/14/S2_Gear_Shoes_Green_Laceups.png"),
            Wearable("Green Rain Boots", "Shoes", "Stealth Jump", 2, "5/51/S2_Gear_Shoes_Green_Rain_Boots.png"),
            Wearable("Hero Runner Replicas", "Shoes", "Quick Super Jump", 2, "b/b6/S2_Gear_Shoes_Hero_Runner_Replicas.png"),
            Wearable("Hero Snowboots Replicas", "Shoes", "Ink Saver (Sub)", 2, "e/ed/S2_Gear_Shoes_Hero_Snowboots_Replicas.png"),
            Wearable("Honey & Orange Squidkid V", "Shoes", "Ink Saver (Sub)", 2, "4/40/S2_Gear_Shoes_Honey_%26_Orange_Squidkid_V.png"),
            Wearable("Hunter Hi-Tops", "Shoes", "Ink Recovery Up", 1, "4/4c/S2_Gear_Shoes_Hunter_Hi-Tops.png"),
            Wearable("Hunting Boots", "Shoes", "Bomb Defense Up DX", 3, "d/d0/S2_Gear_Shoes_Hunting_Boots.png"),
            Wearable("Icy Down Boots", "Shoes", "Stealth Jump", 3, "9/96/S2_Gear_Shoes_Icy_Down_Boots.png"),
            Wearable("Inky Kid Clams", "Shoes", "Ink Recovery Up", 3, "f/fd/S2_Gear_Shoes_Inky_Kid_Clams.png"),
            Wearable("Kid Clams", "Shoes", "Special Power Up", 3, "a/ad/S2_Gear_Shoes_Kid_Clams.png"),
            Wearable("LE Lo-Tops", "Shoes", "Ink Saver (Sub)", 3, "8/80/S2_Gear_Shoes_LE_Lo-Tops.png"),
            Wearable("LE Soccer Shoes", "Shoes", "Ink Resistance Up", 3, "7/7e/S2_Gear_Shoes_LE_Soccer_Shoes.png"),
            Wearable("Luminous Delta Straps", "Shoes", "Main Power Up", 2, "9/95/S2_Gear_Shoes_Luminous_Delta_Straps.png"),
            Wearable("Marinated Slip-Ons", "Shoes", "Ink Recovery Up", 2, "8/84/S2_Gear_Shoes_Marinated_Slip-Ons.png"),
            Wearable("Marination Lace-Ups", "Shoes", "Special Power Up", 3, "0/0e/S2_Gear_Shoes_Marination_Lace-Ups.png"),
            Wearable("Mawcasins", "Shoes", "Ink Recovery Up", 2, "b/b4/S2_Gear_Shoes_Mawcasins.png"),
            Wearable("Mecha Legs LBS", "Shoes", "Object Shredder", 3, "4/40/S2_Gear_Shoes_Mecha_Legs_-_LBS.png"),
            Wearable("Midnight Slip-Ons", "Shoes", "Object Shredder", 3, "e/ee/S2_Gear_Shoes_Midnight_Slip-Ons.png"),
            Wearable("Milky Enperrials", "Shoes", "Swim Speed Up", 3, "b/bf/S2_Gear_Shoes_Milky_Enperrials.png"),
            Wearable("Mint Dakroniks", "Shoes", "Drop Roller", 1, "d/da/S2_Gear_Shoes_Mint_Dakroniks.png"),
            Wearable("Moist Ghillie Boots", "Shoes", "Object Shredder", 3, "7/70/S2_Gear_Shoes_Moist_Ghillie_Boots.png"),
            Wearable("Moto Boots", "Shoes", "Quick Respawn", 2, "3/30/S2_Gear_Shoes_Moto_Boots.png"),
            Wearable("Musselforge Flip-Flops", "Shoes", "Ink Saver (Sub)", 1, "3/37/S2_Gear_Shoes_Musselforge_Flip-Flops.png"),
            Wearable("N-Pacer Ag", "Shoes", "Ink Recovery Up", 2, "2/28/S2_Gear_Shoes_N-Pacer_Ag.png"),
            Wearable("N-Pacer Au", "Shoes", "Quick Respawn", 3, "c/cd/S2_Gear_Shoes_N-Pacer_Au.png"),
            Wearable("N-Pacer CaO", "Shoes", "Object Shredder", 2, "f/f1/S2_Gear_Shoes_N-Pacer_CaO.png"),
            Wearable("Navy Enperrials", "Shoes", "Ink Saver (Main)", 3, "9/97/S2_Gear_Shoes_Navy_Enperrials.png"),
            Wearable("Navy Red-Soled Wingtips", "Shoes", "Ink Saver (Main)", 2, "e/ef/S2_Gear_Shoes_Navy_Red-Soled_Wingtips.png"),
            Wearable("Neo Octoling Snowboots", "Shoes", "Object Shredder", 2, "e/e4/S2_Gear_Shoes_Neo_Octoling_Boots.png"),
            Wearable("Neon Delta Straps", "Shoes", "Sub Power Up", 2, "7/77/S2_Gear_Shoes_Neon_Delta_Straps.png"),
            Wearable("Neon Sea Slugs", "Shoes", "Ink Resistance Up", 1, "a/aa/S2_Gear_Shoes_Neon_Sea_Slugs.png"),
            Wearable("New-Day Arrows", "Shoes", "Ink Recovery Up", 3, "6/62/S2_Gear_Shoes_New-Day_Arrows.png"),
            Wearable("New-Leaf Leather Boots", "Shoes", "Drop Roller", 2, "4/4f/S2_Gear_Shoes_New-Leaf_Leather_Boots.png"),
            Wearable("Non-slip Senseis", "Shoes", "Random", 3, "3/3f/S2_Gear_Shoes_Non-slip_Senseis.png"),
            Wearable("Null Boots Replica", "Shoes", "Drop Roller", 2, "a/a5/S2_Gear_Shoes_Null_Boots_Replica.png"),
            Wearable("Old-Timey Shoes", "Shoes", "Run Speed Up", 2, "f/fb/S2_Gear_Shoes_Old-Timey_Shoes.png"),
            Wearable("Online Squidkid V", "Shoes", "Stealth Jump", 3, "a/a3/S2_Gear_Shoes_Online_Squidkid_V.png"),
            Wearable("Orange Arrows", "Shoes", "Ink Saver (Main)", 1, "9/94/S2_Gear_Shoes_Orange_Arrows.png"),
            Wearable("Orange Iromaki 750s", "Shoes", "Drop Roller", 1, "1/19/S2_Gear_Shoes_Orange_Iromaki_750s.png"),
            Wearable("Orange Lo-Tops", "Shoes", "Swim Speed Up", 1, "b/b7/S2_Gear_Shoes_Orange_Lo-Tops.png"),
            Wearable("Orca Hi-Tops", "Shoes", "Special Saver", 2, "6/6d/S2_Gear_Shoes_Orca_Hi-Tops.png"),
            Wearable("Orca Passion Hi-Tops", "Shoes", "Ink Saver (Sub)", 2, "2/2c/S2_Gear_Shoes_Orca_Passion_Hi-Tops.png"),
            Wearable("Orca Woven Hi-Tops", "Shoes", "Run Speed Up", 2, "9/9a/S2_Gear_Shoes_Orca_Woven_Hi-Tops.png"),
            Wearable("Oyster Clogs", "Shoes", "Run Speed Up", 1, "0/01/S2_Gear_Shoes_Oyster_Clogs.png"),
            Wearable("Pearl Punk Crowns", "Shoes", "Ink Saver (Main)", 3, "e/e7/S2_Gear_Shoes_Pearl_Punk_Crowns.png"),
            Wearable("Pearl-Scout Lace-Ups", "Shoes", "Quick Super Jump", 3, "e/e1/S2_Gear_Shoes_Pearl-Scout_Lace-Ups.png"),
            Wearable("Pearlescent Kicks", "Shoes", "Special Charge Up", 2, "8/8c/S2_Gear_Shoes_Pearlescent_Kicks.png"),
            Wearable("Pearlescent Squidkid IV", "Shoes", "Drop Roller", 3, "b/bb/S2_Gear_Shoes_Pearlescent_Squidkid_IV.png"),
            Wearable("Pink Trainers", "Shoes", "Sub Power Up", 1, "1/15/S2_Gear_Shoes_Pink_Trainers.png"),
            Wearable("Piranha Moccasins", "Shoes", "Stealth Jump", 3, "e/e0/S2_Gear_Shoes_Piranha_Moccasins.png"),
            Wearable("Plum Casuals", "Shoes", "Object Shredder", 2, "d/d4/S2_Gear_Shoes_Plum_Casuals.png"),
            Wearable("Poka-dot Slip-Ons", "Shoes", "Drop Roller", 2, "f/f3/S2_Gear_Shoes_Polka-dot_Slip-Ons.png"),
            Wearable("Power Boots", "Shoes", "Ink Saver (Main)", 2, "3/38/S2_Gear_Shoes_Power_Boots.png"),
            Wearable("Power Boots Mk I", "Shoes", "Bomb Defense Up DX", 2, "e/ee/S2_Gear_Shoes_Power_Boots_Mk_I.png"),
            Wearable("Pro Trail Boots", "Shoes", "Ink Resistance Up", 3, "c/c0/S2_Gear_Shoes_Pro_Trail_Boots.png"),
            Wearable("Punk Blacks", "Shoes", "Main Power Up", 3, "3/32/S2_Gear_Shoes_Punk_Blacks.png"),
            Wearable("Punk Cherries", "Shoes", "Bomb Defense Up DX", 3, "5/55/S2_Gear_Shoes_Punk_Cherries.png"),
            Wearable("Punk Whites", "Shoes", "Special Charge Up", 2, "c/cc/S2_Gear_Shoes_Punk_Whites.png"),
            Wearable("Punk Yellows", "Shoes", "Special Saver", 2, "3/3e/S2_Gear_Shoes_Punk_Yellows.png"),
            Wearable("Purple Hi-Horses", "Shoes", "Special Power Up", 1, "3/33/S2_Gear_Shoes_Purple_Hi-Horses.png"),
            Wearable("Purple Iromaki 750s", "Shoes", "Swim Speed Up", 1, "5/51/S2_Gear_Shoes_Purple_Iromaki_750s.png"),
            Wearable("Purple Sea Slugs", "Shoes", "Run Speed Up", 2, "c/c5/S2_Gear_Shoes_Purple_Sea_Slugs.png"),
            Wearable("Red & Black Squidkid IV", "Shoes", "Special Charge Up", 3, "0/05/S2_Gear_Shoes_Red_%26_Black_Squidkid_IV.png"),
            Wearable("Red & White Squidkid V", "Shoes", "Run Speed Up", 3, "7/7d/S2_Gear_Shoes_Red_%26_White_Squidkid_V.png"),
            Wearable("Red FishFry Sandals", "Shoes", "Object Shredder", 2, "6/66/S2_Gear_Shoes_Red_FishFry_Sandals.png"),
            Wearable("Red Hi-Horses", "Shoes", "Ink Saver (Main)", 1, "0/0b/S2_Gear_Shoes_Red_Hi-Horses.png"),
            Wearable("Red Hi-Tops", "Shoes", "Ink Resistance Up", 2, "7/73/S2_Gear_Shoes_Red_Hi-Tops.png"),
            Wearable("Red Iromaki 750s", "Shoes", "Ink Saver (Sub)", 1, "b/bf/S2_Gear_Shoes_Red_Iromaki_750s.png"),
            Wearable("Red Power Stripes", "Shoes", "Run Speed Up", 2, "7/76/S2_Gear_Shoes_Red_Power_Stripes.png"),
            Wearable("Red Sea Slugs", "Shoes", "Special Saver", 3, "d/d9/S2_Gear_Shoes_Red_Sea_Slugs.png"),
            Wearable("Red Slip-Ons", "Shoes", "Quick Super Jump", 1, "d/d8/S2_Gear_Shoes_Red_Slip-Ons.png"),
            Wearable("Red Work Boots", "Shoes", "Quick Super Jump", 3, "6/60/S2_Gear_Shoes_Red_Work_Boots.png"),
            Wearable("Red-Mesh Sneakers", "Shoes", "Special Power", 2, "1/1a/S2_Gear_Shoes_Red-Mesh_Sneakers.png"),
            Wearable("Rina Squidkid IV", "Shoes", "Bomb Defense Up DX", 3, "f/f1/S2_Gear_Shoes_Rina_Squidkid_IV.png"),
            Wearable("Roasted Brogues", "Shoes", "Bomb Defense Up DX", 1, "7/73/S2_Gear_Shoes_Roasted_Brogues.png"),
            Wearable("Samurai Shoes", "Shoes", "Special Power Up", 2, "9/9d/S2_Gear_Shoes_Samurai_Shoes.png"),
            Wearable("School Shoes", "Shoes", "Ink Saver (Sub)", 2, "a/a2/S2_Gear_Shoes_School_Shoes.png"),
            Wearable("Sea Slug Volt 95s", "Shoes", "Ink Saver (Sub)", 2, "5/55/S2_Gear_Shoes_Sea_Slug_Volt_95s.png"),
            Wearable("Sennyu Inksoles", "Shoes", "Stealth Jump", 3, "b/b9/S2_Gear_Shoes_Sennyu_Inksoles.png"),
            Wearable("Sesame Salt 270s", "Shoes", "Quick Super Jump", 2, "7/74/S2_Gear_Shoes_Sesame_Salt_270s.png"),
            Wearable("Shark Moccasins", "Shoes", "Sub Power Up", 1, "4/40/S2_Gear_Shoes_Shark_Moccasins.png"),
            Wearable("Smoky Wingtips", "Shoes", "Object Shredder", 3, "7/78/S2_Gear_Shoes_Smoky_Wingtips.png"),
            Wearable("Snow Delta Straps", "Shoes", "Swim Speed Up", 3, "6/6e/S2_Gear_Shoes_Snow_Delta_Straps.png"),
            Wearable("Snowy Down Boots", "Shoes", "Quick Super Jump", 3, "6/6e/S2_Gear_Shoes_Snowy_Down_Boots.png"),
            Wearable("Soccer Shoes", "Shoes", "Bomb Defense Up DX", 3, "7/7a/S2_Gear_Shoes_Soccer_Shoes.png"),
            Wearable("Squid-Stitch Slip-Ons", "Shoes", "Bomb Defense Up DX", 2, "9/93/S2_Gear_Shoes_Squid-Stitch_Slip-Ons.png"),
            Wearable("Squinja Boots", "Shoes", "Swim Speed Up", 2, "a/ad/S2_Gear_Shoes_Squinja_Boots.png"),
            Wearable("Squink Wingtips", "Shoes", "Quick Respawn", 1, "f/fc/S2_Gear_Shoes_Squink_Wingtips.png"),
            Wearable("Steel Greaves", "Shoes", "Object Shredder", 2, "b/ba/S2_Gear_Shoes_Steel_Greaves.png"),
            Wearable("Strapping Reds", "Shoes", "Ink Resistance Up", 1, "3/34/S2_Gear_Shoes_Strapping_Reds.png"),
            Wearable("Strapping Whites", "Shoes", "Ink Saver (Sub)", 3, "4/45/S2_Gear_Shoes_Strapping_Whites.png"),
            Wearable("Suede Gray Lace-Ups", "Shoes", "Ink Recovery Up", 1, "f/f1/S2_Gear_Shoes_Suede_Gray_Lace-Ups.png"),
            Wearable("Suede Marine Lace-Ups", "Shoes", "Ink Resistance Up", 1, "7/72/S2_Gear_Shoes_Suede_Marine_Lace-Ups.png"),
            Wearable("Suede Nation Lace-Ups", "Shoes", "Ink Saver (Main)", 2, "4/41/S2_Gear_Shoes_Suede_Nation_Lace-Ups.png"),
            Wearable("Sun & Shade Squidkid IV", "Shoes", "Main Power Up", 3, "a/af/S2_Gear_Shoes_Sun_%26_Shade_Squidkid_IV.png"),
            Wearable("Sunny Climbing Shoes", "Shoes", "Special Saver", 2, "6/6d/S2_Gear_Shoes_Sunny_Climbing_Shoes.png"),
            Wearable("Sunset Orca Hi-Tops", "Shoes", "Drop Roller", 2, "4/47/S2_Gear_Shoes_Sunset_Orca_Hi-Tops.png"),
            Wearable("Tan Work Boots", "Shoes", "Sub Power Up", 2, "f/ff/S2_Gear_Shoes_Tan_Work_Boots.png"),
            Wearable("Tea-Green Hunting Boots", "Shoes", "Quick Respawn", 3, "8/8d/S2_Gear_Shoes_Tea-Green_Hunting_Boots.png"),
            Wearable("Toni Kensa Black Hi-Tops", "Shoes", "Sub Power Up", 3, "0/0d/S2_Gear_Shoes_Toni_Kensa_Black_Hi-Tops.png"),
            Wearable("Toni Kensa Soccer Shoes", "Shoes", "Ink Saver (Main)", 3, "c/c2/S2_Gear_Shoes_Toni_Kensa_Soccer_Shoes.png"),
            Wearable("Trail Boots", "Shoes", "Ink Recovery Up", 3, "e/ef/S2_Gear_Shoes_Trail_Boots.png"),
            Wearable("Trooper Power Stripes", "Shoes", "Sub Power Up", 3, "a/a1/S2_Gear_Shoes_Trooper_Power_Stripes.png"),
            Wearable("Truffle Canvas Hi-Tops", "Shoes", "Special Power Up", 1, "9/91/S2_Gear_Shoes_Truffle_Canvas_Hi-Tops.png"),
            Wearable("Turquoise Kicks", "Shoes", "Special Charge Up", 2, "7/70/S2_Gear_Shoes_Turquoise_Kicks.png"),
            Wearable("Violet Trainers", "Shoes", "Object Shredder", 1, "9/92/S2_Gear_Shoes_Violet_Trainers.png"),
            Wearable("White Arrows", "Shoes", "Special Power Up", 2, "2/25/S2_Gear_Shoes_White_Arrows.png"),
            Wearable("White Kicks", "Shoes", "Swim Speed Up", 1, "5/56/S2_Gear_Shoes_White_Kicks.png"),
            Wearable("White Laceless Dakroniks", "Shoes", "Run Speed Up", 2, "9/96/S2_Gear_Shoes_White_Laceless_Dakroniks.png"),
            Wearable("White Iromaki 750s", "Shoes", "Swim Speed Up", 2, "3/39/S2_Gear_Shoes_White_Norimaki_750s.png"),
            Wearable("White Seahorses", "Shoes", "Ink Recovery Up", 1, "a/ad/S2_Gear_Shoes_White_Seahorses.png"),
            Wearable("Wooden Sandals", "Shoes", "Random", 3, "c/c7/S2_Gear_Shoes_Wooden_Sandals.png"),
            Wearable("Yellow FishFry Sandals", "Shoes", "Main Power Up", 2, "f/f7/S2_Gear_Shoes_Yellow_FishFry_Sandals.png"),
            Wearable("Yellow Iromaki 750s", "Shoes", "Special Saver", 1, "4/4f/S2_Gear_Shoes_Yellow_Iromaki_750s.png"),
            Wearable("Yellow Seahorses", "Shoes", "Bomb Defense Up DX", 2, "7/7d/S2_Gear_Shoes_Yellow_Seahorses.png"),
            Wearable("Yellow-Mesh Sneakers", "Shoes", "Main Power Up", 1, "a/a3/S2_Gear_Shoes_Yellow-Mesh_Sneakers.png"),
            Wearable("Zombie Hi-Horses", "Shoes", "Special Charge Up", 1, "4/47/S2_Gear_Shoes_Zombie_Hi-Horses.png")
            )
    }

}